---
- name: register the server
  hosts: all
  tasks:
    - name: register
      command: subscription-manager register --username "{{ rh_username }}" --password "{{ rh_password }}" --force

    - name: attach to pool
      command: subscription-manager attach --pool="{{ rh_poolid }}"
      register: register_result
